

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider  , SignedOut , SignedIn, SignInButton , UserButton  , SignUpButton , SignUp} from "@/node_modules/@clerk/nextjs/dist/types";
import "./globals.css";
import { User } from "@/node_modules/@clerk/nextjs/dist/types/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <ClerkProvider>
              <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

              <section>
                <SignedOut>
                    <SignUpButton/>
                </SignedOut>
              </section>

              <SignedIn> {children} </SignedIn>

              </body>
              </html>

        </ClerkProvider>
  );
}
